// Copies contract ABIs and deployed addresses into the frontend as a typed TS module.
// Runs automatically after `pnpm deploy:local` / `pnpm deploy:monad`.
// Usage: node scripts/export-web.ts
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";

const OUT = "web/src/contracts/generated.ts";
const DEPLOYMENTS_DIR = "ignition/deployments";

function readJson(path: string) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function abiOf(contract: string) {
  return readJson(`artifacts/contracts/${contract}.sol/${contract}.json`).abi;
}

const deployments: Record<string, unknown> = {};
if (existsSync(DEPLOYMENTS_DIR)) {
  for (const dir of readdirSync(DEPLOYMENTS_DIR).sort()) {
    const chainId = dir.match(/^chain-(\d+)$/)?.[1];
    const file = `${DEPLOYMENTS_DIR}/${dir}/deployed_addresses.json`;
    if (chainId === undefined || !existsSync(file)) continue;

    const addresses = readJson(file);
    deployments[chainId] = {
      pair: addresses["BlitzSwap#BlitzPair"],
      // The Ignition module passes BLTZ first, so it is the pair's token0.
      token0: { symbol: "BLTZ", address: addresses["BlitzSwap#BLTZ"] },
      token1: { symbol: "mUSD", address: addresses["BlitzSwap#mUSD"] },
    };
  }
}

const json = (value: unknown) => JSON.stringify(value, null, 2);
writeFileSync(
  OUT,
  `// Generated by scripts/export-web.ts. Do not edit by hand.
// \`as const\` lets viem/wagmi infer exact function names and argument types from the ABIs.

export const blitzTokenAbi = ${json(abiOf("BlitzToken"))} as const;

export const blitzPairAbi = ${json(abiOf("BlitzPair"))} as const;

export const deployments = ${json(deployments)} as const;
`,
);

console.log(`Wrote ${OUT} (chains: ${Object.keys(deployments).join(", ") || "none"})`);
